## **Prédiction avec la regression logistique sur le jeu de données**

Objectif : test de prédiction des valeurs processed avec le modèle **Regression logistique**

In [29]:
# Import des librairies 
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

In [2]:
# Regression logistique 
from sklearn import linear_model
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import GridSearchCV, train_test_split

In [14]:
# Les dossiers data 
from pathlib import Path

# Les dossiers data
root = Path.cwd().resolve()
if not (root / "data").exists() and (root.parent / "data").exists():
    root = root.parent

HISTO_DATA_DIR = str((root / "data" /"processed"/ "histogramme").as_posix()) + "/"

In [27]:
# Charger les fonctions utils : 
from src.utils import load_processed

# Une seule ligne, 4 variables, toujours dans cet ordre
x_train, x_test, y_train, y_test = load_processed("histogramme")

ModuleNotFoundError: No module named 'src'

In [25]:
# Les train et test sets sont déjà créés dans le notebook précédent, nous allons les charger
X_hist_train = HISTO_DATA_DIR + "X_train.csv"
X_hist_test = HISTO_DATA_DIR + "X_test.csv"

Y_hist_train = HISTO_DATA_DIR + "Y_train.csv"
Y_hist_test = HISTO_DATA_DIR + "Y_test.csv"

In [23]:
pd.read_csv(HISTO_DATA_DIR + "x_train.csv")

,ps2_bin_0,ps2_bin_13,ps2_bin_14,ps2_bin_15,ps2_bin_16,fs1_bin_0,fs1_bin_4,fs1_bin_5,fs1_bin_6,fs1_bin_8,fs1_bin_9,fs1_bin_10,fs1_bin_11,fs1_bin_12
0,0.153167,0.000167,0.338833,0.336833,0.167500,0.156667,0.005000,0.005000,0.005000,0.016667,0.005000,0.003333,0.003333,0.001667
1,0.153000,0.000167,0.322500,0.351667,0.169333,0.155000,0.003333,0.003333,0.003333,0.020000,0.006667,0.003333,0.003333,0.000000
2,0.152833,0.000167,0.326167,0.348000,0.169333,0.155000,0.003333,0.003333,0.005000,0.020000,0.008333,0.003333,0.001667,0.001667
3,0.152833,0.000167,0.323167,0.350667,0.169500,0.155000,0.003333,0.003333,0.003333,0.020000,0.006667,0.003333,0.003333,0.000000
4,0.153333,0.000167,0.339667,0.336333,0.167500,0.158333,0.006667,0.001667,0.003333,0.016667,0.011667,0.003333,0.001667,0.003333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1759,0.152500,0.007333,0.330833,0.338167,0.167167,0.155000,0.003333,0.006667,0.006667,0.005000,0.006667,0.003333,0.000000,0.003333
1760,0.153167,0.148000,0.188500,0.009667,0.006833,0.168333,0.001667,0.000000,0.001667,0.010000,0.003333,0.003333,0.001667,0.003333
1761,0.153000,0.000000,0.340000,0.336167,0.167500,0.156667,0.001667,0.006667,0.006667,0.018333,0.008333,0.005000,0.001667,0.001667
1762,0.152500,0.003833,0.334167,0.338333,0.167333,0.155000,0.003333,0.005000,0.006667,0.005000,0.006667,0.003333,0.000000,0.003333
1763,0.157167,0.147167,0.252333,0.275000,0.164500,0.161667,0.003333,0.001667,0.006667,0.000000,0.000000,0.003333,0.000000,0.001667

In [21]:
pd.read_csv(HISTO_DATA_DIR + "X_test.csv")

,ps2_bin_0,ps2_bin_13,ps2_bin_14,ps2_bin_15,ps2_bin_16,fs1_bin_0,fs1_bin_4,fs1_bin_5,fs1_bin_6,fs1_bin_8,fs1_bin_9,fs1_bin_10,fs1_bin_11,fs1_bin_12
0,0.157333,0.000000,0.333500,0.336833,0.167667,0.161667,0.005000,0.003333,0.005000,0.021667,0.008333,0.003333,0.001667,0.001667
1,0.153833,0.026667,0.313167,0.335500,0.167167,0.158333,0.003333,0.003333,0.010000,0.005000,0.005000,0.003333,0.003333,0.001667
2,0.154167,0.000000,0.338500,0.335833,0.167833,0.158333,0.005000,0.005000,0.005000,0.016667,0.005000,0.001667,0.001667,0.003333
3,0.157500,0.000333,0.327000,0.342333,0.168667,0.161667,0.001667,0.006667,0.006667,0.013333,0.005000,0.003333,0.003333,0.001667
4,0.152833,0.000167,0.324000,0.350167,0.169333,0.155000,0.003333,0.003333,0.003333,0.020000,0.008333,0.005000,0.003333,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436,0.153167,0.151333,0.187667,0.340500,0.164000,0.155000,0.001667,0.003333,0.008333,0.005000,0.001667,0.003333,0.003333,0.001667
437,0.155833,0.000000,0.336500,0.336333,0.167667,0.160000,0.005000,0.003333,0.005000,0.016667,0.003333,0.003333,0.003333,0.000000
438,0.154333,0.000000,0.338667,0.336167,0.167333,0.158333,0.006667,0.003333,0.006667,0.018333,0.006667,0.003333,0.001667,0.003333
439,0.155667,0.000167,0.325500,0.345667,0.169333,0.158333,0.001667,0.006667,0.006667,0.016667,0.008333,0.003333,0.001667,0.003333
440,0.153500,0.000167,0.341333,0.335167,0.167167,0.155000,0.006667,0.001667,0.005000,0.015000,0.010000,0.003333,0.001667,0.001667

In [ ]:
modele_reglog = linear_model.LogisticRegression()
modele_reglog.fit(X_hist_train, Y_hist_train)

y_hist_pred = modele_reglog.predict(X_hist_test)

precison = modele_reglog.score(X_hist_train, X_hist_test)